### ISSUE TITLE
Please Add A License

### ISSUE THREAD

**Issue by postables** [backkem/go-libp2p-webrtc-direct#1]
Hello, I saw your comment on an issue on the [libp2p/go-libp2p#188](https://github.com/libp2p/go-libp2p/issues/188), and would like to use this libp2p transport for an experimental feature in one of my projects. If that feature goes well, more than likely can contribute to this library as I would need to use it a lot. 

Projects that do not include a license, are technically not usable by other projects https://choosealicense.com/no-permission/ 

Thanks!

**Comment by backkem** [comment]
Hi @postables. I added an MIT license. This repo is currently in a proof of concept stage.
I've been busy working on the core WebRTC library at pions/webrtc in the mean time. I do intent to get this library in a usable state at some point.

Some things I think need looking at:
- Get some dependencies to land:
  - [ ] [mafmt](https://github.com/whyrusleeping/mafmt/pull/14)
  - [ ] [go-multiaddr-dns](https://github.com/multiformats/go-multiaddr-dns/pull/11)
  - [x] [go-multiaddr](https://github.com/multiformats/go-multiaddr/pull/93)
- Determine if committing to [pions/dcnet](https://github.com/pions/dcnet)
- Upgrade to a newer version of [pions/webrtc](https://github.com/pions/webrtc).
- Migrate to the [Detach API](https://github.com/pions/webrtc/tree/master/examples/data-channels-detach) (in pions/dcnet if keeping it).
- Implement the libp2p interfaces correctly instead of relying on the `*tptu.Upgrader`.
- Fix all the error handling I skipped.
- Make the tests green.
- Integration testing with js-libp2p-webrtc-direct

Long term I would prefer to contribute this library to the libp2p project itself, if/when they're willing to have it. You can also find me in the libp2p IRC or the Pion channel on the Golang slack if you have questions.

**Comment by postables** [comment]
Awesome thank you! I'll be starting this project within the next 2-3 weeks, so if there's anything that should be tackled first let me know, otherwise i'll just poke around and open an issue if i find anything, or a pr if i see an immediate room for improvement.

Thanks for creating this library, will save a ton of initial work :fire:

**Comment by backkem** [comment]
Rewriting in #2 to fix the issues mentioned above.
